remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already have one
relative_links:
  enabled: true
  collections: true
include:
  - Overview.md
  - Creating an Analysis of Your Commodities.md
  - Viewing Your CommodityMap Analysis.md
  - Comparing CommodityMap Analysis.md


